### ISSUE TITLE
Receive Push Notifications

### ISSUE THREAD

**Issue by brandecho** [proximiio/proximiio-cordova#1]
Does not provide detail on how to implement receiving push notifications. 
Does this plugin require the cordova/phonegap plugin (phonegap-plugin-push)? 
Where is the function "proximiio.setHandlePush(true);" added?  When added on line #40 of the index.js file, get an error in the console stating "Uncaught Exception". 
Also missing instructions on implementing Google's new Firebase Cloud Messaging API and including the google-services.json. Is this required? 
Overall.. all beacons setup in portal are found but not receiving push notifications from actions set.

**Comment by MikaKoskiola** [comment]
Hey,

It seems that we have an error in our docs which will be fixed shortly. It should be "proximiio.handlePush(true);".

Using phonegap-plugin-push or any other third party stuff is not required if you wish to leverage our local push notifications.

Let me know if you're still having issues.

**Comment by brandecho** [comment]
Thank you @MikaKoskiola . Can you please provide the location of where the function "proximiio.handlePush(true);" should be placed within the "proximiio-cordova-demo", so the function is called within the onDeviceReady event? An example would be great!  In the Github file (https://github.com/proximiio/proximiio-cordova-demo) located at [proximiio-cordova-demo/www/js/index.js](https://github.com/proximiio/proximiio-cordova-demo/blob/master/www/js/index.js) from line# 33 to 43, we entered the code below and still getting an error. See code below.
`
onDeviceReady: function () {
    proximiio.setToken(PROXIMIIO_TOKEN);
    proximiio.setDebugOutput(true);
    proximiio.handlePush(true);
    proximiio.setOutputTriggerCallback(function (output) {
      document.getElementById('output').innerHTML = '<pre>' + formatJson(output) + '</pre>';
    });
`
