### ISSUE TITLE
Question:  Can I record the user's location while the app is closed and/or in the background?

### ISSUE THREAD

**Issue by mikepsinn** [proximiio/proximiio-cordova#2]
Is it possible to record the user's location while the app is closed and/or in the background in an ongoing manner on iOS and/or Android?

**Comment by MikaKoskiola** [comment]
Yes, our SDK automatically creates a background service which sends the position updates to our backend. These position updates are available via our REST API. If the user enters / exits a defined geofence, an event is automatically triggered, too.

**Comment by mikepsinn** [comment]
Thanks!
