### ISSUE TITLE
Plugin add Error (on Windows)

### ISSUE THREAD

**Issue by Florian007** [proximiio/proximiio-cordova#5]
Trying to add the plugin with:
cordova plugin add https://github.com/proximiio/proximiio-cordova.git

Get the following Error: Failed to fetch plugin https://github.com/proximiio/proximiio-cordova.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install C:\Users\USER\AppData\Local\Temp\npm-12376-33408620\git-cach
e-091655be\726ea7ba915ce566a1ec5beb65312a6468bc63a7
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\
\bin\\npm-cli.js" "install" "https://github.com/proximiio/proximiio-cordova.git" "--save"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2017-07-13T14_49_41_697Z-debug.log

Also if I  download it locally and try to add with:
cordova plugin add /downloads/navtureapps-proximiio
I get the error: Registry returned 404 for GET on https://registry.npmjs.org/aktionsfinder

I am using cordova version 7.0.1 and android platform version 6.2.1

Thank you!

**Comment by MikaKoskiola** [comment]
On a first peek this looked like an issue I've seen with Ionic behind a proxy but I think this is due to some changes in the Cordova version 7 regarding plugins. Can you try to run "npm init" in the cloned / downloaded plugin directory and see how the local plugin installation behaves? You can just hit enter throughout the "npm init" wizard.

Let me know if this solved your problem and I'll do a commit with a fully detailed package.json to our official repository.

**Comment by Florian007** [comment]
Yes, the local plugin installation after "npm init" did work. Thank you!

**Comment by MikaKoskiola** [comment]
Okay, thanks for the info. We'll update the repository to include the package.json too.
